//! Nostr protocol contract for the x0x bridge — FROZEN during module phase.
//!
//! Module owners: store.rs, transport.rs, relay.rs implement against these
//! types. Do not edit this file; report contract gaps to the coordinator.

use nostr::Alphabet;
use nostr::{Event, Filter, Kind, SingleLetterTag, Timestamp};

// ---- Limits (mirror buzz-relay) ----
pub const MAX_FRAME_BYTES: usize = 65_536;
pub const MAX_SUBS_PER_CONN: usize = 1024;
pub const MAX_FILTER_LIMIT: usize = 500;
pub const SEND_QUEUE: usize = 1024;
pub const SLOW_CLIENT_GRACE: u32 = 3;
pub const AUTH_KIND: u16 = 22242;
pub const AUTH_MAX_AGE_SECS: u64 = 600;
/// Max allowed clock skew into the FUTURE for an auth event's created_at
/// (tighter than the past window to block future-dated auth-event replay).
pub const AUTH_MAX_FUTURE_SKEW_SECS: u64 = 60;

// ---- Gossip topic mapping ----
pub const GLOBAL_TOPIC: &str = "buzz.v1.global";
pub const CHANNEL_TOPIC_PREFIX: &str = "buzz.v1.ch.";

pub fn channel_topic(channel_id: &str) -> String {
    format!("{CHANNEL_TOPIC_PREFIX}{}", channel_id.to_lowercase())
}

/// Lowercased `h` tag values of an event (NIP-29 channel ids).
pub fn event_channels(ev: &Event) -> Vec<String> {
    let mut out: Vec<String> = ev
        .tags
        .iter()
        .filter(|t| t.as_slice().first().map(String::as_str) == Some("h"))
        .filter_map(|t| t.as_slice().get(1).map(|s| s.to_lowercase()))
        .collect();
    out.sort();
    out.dedup();
    out
}

/// Gossip topics an event is published to: one per `h` tag, else global.
pub fn topics_for_event(ev: &Event) -> Vec<String> {
    let chans = event_channels(ev);
    if chans.is_empty() {
        vec![GLOBAL_TOPIC.to_string()]
    } else {
        chans.iter().map(|c| channel_topic(c)).collect()
    }
}

/// `h` values requested by a filter (`#h` generic tag query).
pub fn filter_channels(f: &Filter) -> Vec<String> {
    f.generic_tags
        .get(&SingleLetterTag::lowercase(Alphabet::H))
        .map(|vals| vals.iter().map(|s| s.to_lowercase()).collect())
        .unwrap_or_default()
}

// ---- Kind classes (NIP-16) ----
pub fn is_ephemeral(kind: Kind) -> bool {
    (20_000..30_000).contains(&kind.as_u16())
}
pub fn is_replaceable(kind: Kind) -> bool {
    let k = kind.as_u16();
    k == 0 || k == 3 || (10_000..20_000).contains(&k)
}
pub fn is_parameterized_replaceable(kind: Kind) -> bool {
    (30_000..40_000).contains(&kind.as_u16())
}

/// First `d` tag value (parameterized-replaceable address).
pub fn d_tag(ev: &Event) -> Option<String> {
    ev.tags
        .iter()
        .find(|t| t.as_slice().first().map(String::as_str) == Some("d"))
        .and_then(|t| t.as_slice().get(1).cloned())
}

// ---- Verification ----

/// Verify NIP-01 id hash + Schnorr signature.
pub fn verify_event(ev: &Event) -> anyhow::Result<()> {
    ev.verify()
        .map_err(|e| anyhow::anyhow!("event verification failed: {e}"))
}

/// Compare two relay WS URLs for NIP-42 equality, tolerating a trailing slash
/// (clients derive the tag from the relay URL, which may or may not end in `/`).
fn relay_url_matches(actual: &str, expected: &str) -> bool {
    actual.trim_end_matches('/') == expected.trim_end_matches('/')
}

/// Validate a NIP-42 auth event against an expected challenge and, when
/// `expected_relay_url` is `Some`, the NIP-42 `relay` tag (WP3, issue #3:
/// without this an AUTH is replayable across bridges within the time window).
/// `None` skips the relay-tag check (spike/test parity).
pub fn verify_auth_event(
    ev: &Event,
    expected_challenge: &str,
    now: Timestamp,
    expected_relay_url: Option<&str>,
) -> anyhow::Result<()> {
    if ev.kind.as_u16() != AUTH_KIND {
        anyhow::bail!("auth event kind {} != {AUTH_KIND}", ev.kind.as_u16());
    }
    let challenge = ev
        .tags
        .iter()
        .find(|t| t.as_slice().first().map(String::as_str) == Some("challenge"))
        .and_then(|t| t.as_slice().get(1))
        .ok_or_else(|| anyhow::anyhow!("auth event missing challenge tag"))?;
    if challenge != expected_challenge {
        anyhow::bail!("challenge mismatch");
    }
    // NIP-42 relay-tag binding: the signed `relay` tag must equal the tenant's
    // own WS URL, so a challenge/response signed for one relay cannot be
    // replayed against another.
    if let Some(expected) = expected_relay_url {
        let relay = ev
            .tags
            .iter()
            .find(|t| t.as_slice().first().map(String::as_str) == Some("relay"))
            .and_then(|t| t.as_slice().get(1))
            .ok_or_else(|| anyhow::anyhow!("auth event missing relay tag"))?;
        if !relay_url_matches(relay, expected) {
            anyhow::bail!("relay tag mismatch");
        }
    }
    // Asymmetric validity window: a generous `AUTH_MAX_AGE_SECS` into the past
    // (clock drift), but only `AUTH_MAX_FUTURE_SKEW_SECS` into the future to
    // block future-dated auth events.
    let ev_ts = ev.created_at.as_secs();
    let now_ts = now.as_secs();
    if ev_ts > now_ts {
        let skew = ev_ts - now_ts;
        if skew > AUTH_MAX_FUTURE_SKEW_SECS {
            anyhow::bail!("auth event future skew too large ({skew}s)");
        }
    } else {
        let age = now_ts - ev_ts;
        if age > AUTH_MAX_AGE_SECS {
            anyhow::bail!("auth event too old ({age}s)");
        }
    }
    verify_event(ev)
}

#[cfg(test)]
mod tests {
    use super::*;
    use nostr::{EventBuilder, Keys, Tag};

    #[test]
    fn signed_event_verifies_and_maps_topics() {
        let keys = Keys::generate();
        let ev = EventBuilder::new(Kind::from(9u16), "hello")
            .tag(Tag::custom(
                nostr::TagKind::custom("h"),
                ["550e8400-e29b-41d4-a716-446655440000"],
            ))
            .sign_with_keys(&keys)
            .expect("sign");
        verify_event(&ev).expect("valid sig");
        assert_eq!(
            event_channels(&ev),
            ["550e8400-e29b-41d4-a716-446655440000"]
        );
        assert_eq!(
            topics_for_event(&ev),
            ["buzz.v1.ch.550e8400-e29b-41d4-a716-446655440000"]
        );
    }

    #[test]
    fn no_h_tag_goes_global() {
        let keys = Keys::generate();
        let ev = EventBuilder::text_note("profile-ish")
            .sign_with_keys(&keys)
            .expect("sign");
        assert_eq!(topics_for_event(&ev), [GLOBAL_TOPIC]);
    }

    #[test]
    fn kind_classes() {
        assert!(is_ephemeral(Kind::from(20001u16)));
        assert!(!is_ephemeral(Kind::from(9u16)));
        assert!(is_replaceable(Kind::from(0u16)));
        assert!(is_replaceable(Kind::from(10002u16)));
        assert!(is_parameterized_replaceable(Kind::from(30023u16)));
        assert!(!is_parameterized_replaceable(Kind::from(40100u16)));
    }

    #[test]
    fn tampered_event_rejected() {
        let keys = Keys::generate();
        let mut ev = EventBuilder::text_note("hi")
            .sign_with_keys(&keys)
            .expect("sign");
        ev.content.push_str(" tampered");
        assert!(verify_event(&ev).is_err());
    }
}
